export interface RateLimitResult { allowed: boolean; remaining: number; retryAfterMs?: number; }
export interface RateLimitSnapshotEntry { key: string; startedAt: number; count: number; }
export interface RateLimiterOptions { limit: number; windowMs: number; maxEntries?: number; now?: () => number; restored?: RateLimitSnapshotEntry[]; onChange?: (snapshot: RateLimitSnapshotEntry[]) => void; }
export function createRateLimiter(options: RateLimiterOptions) {
  const entries = new Map<string, { startedAt: number; count: number }>(); const now = options.now ?? Date.now; const maxEntries = Math.max(1, Math.floor(options.maxEntries ?? 10_000)); const notify = () => options.onChange?.(Array.from(entries, ([key, entry]) => ({ key, ...entry })));
  for (const restored of options.restored ?? []) if (typeof restored.key === "string" && restored.key.length <= 256 && restored.count > 0) entries.set(restored.key, { startedAt: restored.startedAt, count: restored.count });
  const purge = (timestamp: number) => { let changed = false; for (const [key, entry] of entries) if (timestamp - entry.startedAt >= options.windowMs) { entries.delete(key); changed = true; } while (entries.size > maxEntries) { const oldest = entries.keys().next().value as string | undefined; if (oldest === undefined) break; entries.delete(oldest); changed = true; } if (changed) notify(); };
  return { limit: options.limit, windowMs: options.windowMs, maxEntries, check(key: string): RateLimitResult { const timestamp = now(); purge(timestamp); const current = entries.get(key); if (!current || timestamp - current.startedAt >= options.windowMs) { entries.set(key, { startedAt: timestamp, count: 1 }); notify(); return { allowed: true, remaining: Math.max(0, options.limit - 1) }; } if (current.count >= options.limit) return { allowed: false, remaining: 0, retryAfterMs: Math.max(0, options.windowMs - (timestamp - current.startedAt)) }; current.count += 1; notify(); return { allowed: true, remaining: Math.max(0, options.limit - current.count) }; }, reset() { entries.clear(); notify(); }, snapshot() { purge(now()); return Array.from(entries, ([key, entry]) => ({ key, ...entry })); }, size() { return entries.size; }, has(key: string) { return entries.has(key); } };
}
